CREATE SEQUENCE app_users_seq
/
CREATE SEQUENCE xxgen_companyid_seq
/
CREATE SEQUENCE xxgen_comp_branch_id_seq
/
CREATE SEQUENCE xxgen_prod_id_seq
/
CREATE SEQUENCE xxgen_risk_id_seq
/
CREATE SEQUENCE xxgen_agent_id_seq
/
CREATE SEQUENCE xxgen_SURVEYOR_id_seq
/
CREATE SEQUENCE xxgen_INSURED_id_seq
/
CREATE SEQUENCE xxgen_INSURED_ADDR_id_seq
/
CREATE SEQUENCE xxgen_POLICY_NO_seq
/
CREATE SEQUENCE xxgen_POL_RISK_ID_seq
/
CREATE SEQUENCE xxgen_POL_VEHICLE_ID_seq
/
CREATE SEQUENCE xxgen_V_DRIVER_ID_seq
/
CREATE SEQUENCE xxgen_T_VILATION_ID_seq
/
CREATE SEQUENCE xxgen_BILL_ID_seq
/
CREATE SEQUENCE xxgen_PAYMENT_ID_seq
/
CREATE SEQUENCE xxgen_CLAIM_ID_seq
/
CREATE SEQUENCE xxgen_CLM_PROCESS_ID_seq
/
CREATE SEQUENCE xxgen_CLM_DOC_ID_seq