Insert into  USER_ROLES (ROLE_CODE ,role_desc)
values('UWC','Under Writer policy creation')
/
insert into  USER_ROLES (ROLE_CODE ,role_desc )
values('UWE','Policy Endorsement');
/
insert into  app_users (id ,username,  password,first_name,last_name ,start_date ,end_date,USER_ROLE_CODE)
VALUES (app_users_seq.NEXTVAL,UPPER(p_username),get_hash(p_username, p_password),p_first_name,p_last_name,sysdate,null,'UWC')
/
  CONSTRAINT app_users_uk  (username)
)
/
DROP TABLE XXGEN_COMPANY_MASTER
/
insert into  XXGEN_COMPANY_MASTER(COMPANY_ID  ,COMPANY_CODE   ,COMPANY_NAME ,created_by ,created_date ,last_updated_by ,last_update_date )
values (xxgen_companyid_seq.next_val,'NEWIND','NEW INDIA GENERAL INSURANCE COMPANY',1,sysdate,1,sysdate)
/
insert into  XXGEN_COMPANY_MASTER(COMPANY_ID  ,COMPANY_CODE   ,COMPANY_NAME ,created_by ,created_date ,last_updated_by ,last_update_date )
values (xxgen_companyid_seq.next_val,'HDFCGEN','HDFC GENERAL INSURANCE COMPANY',1,sysdate,1,sysdate)
/
insert into  XXGEN_COMPANY_BRANCH_MASTER
(BRANCH_ID ,BRANCH_CODE,BRANCH_NAME ,COMPANY_ID,ADDR1,ADDR2,BRANCH_CITY,BRANCH_STATE ,BRANCH_COUNTRY ,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_comp_branch_id_seq.NEXTVAL,'NEWINDHYD','NEW INDIA GENERAL INSURANCE HYDERBAD BRANCH',1,'GACHIBOWLI','SERILINGAMPALLI','HYDERABAD','TELENGANA','INDIA',1,sysdate,1,sysdate)
/
insert into  XXGEN_COMPANY_BRANCH_MASTER
(BRANCH_ID ,BRANCH_CODE,BRANCH_NAME ,COMPANY_ID,ADDR1,ADDR2,BRANCH_CITY,BRANCH_STATE ,BRANCH_COUNTRY ,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_comp_branch_id_seq.NEXTVAL,'NEWINDBAN','NEW INDIA GENERAL INSURANCE BANGLORE BRANCH',1,'BTM LAYOUT','BTM','BANGLORE','KALNATAKA','INDIA',1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_MASTER (PROD_ID,PROD_CODE,PROD_DESCRIPTION ,PROD_START_DATE,PROD_END_DATE,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_prod_id_seq.NEXTVAL,'MOTOR2','TWO WHEELER VEHICLE INSURANCE',SYSDATE,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_MASTER (PROD_ID,PROD_CODE,PROD_DESCRIPTION ,PROD_START_DATE,PROD_END_DATE,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_prod_id_seq.NEXTVAL,'MOTOR4','4 WHEELER VEHICLE INSURANCE',SYSDATE,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_MASTER (PROD_ID,PROD_CODE,PROD_DESCRIPTION ,PROD_START_DATE,PROD_END_DATE,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_prod_id_seq.NEXTVAL,'FIRE','FIRE INSURANCE',SYSDATE,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_MASTER (PROD_ID,PROD_CODE,PROD_DESCRIPTION ,PROD_START_DATE,PROD_END_DATE,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_prod_id_seq.NEXTVAL,'HOME','HOME INSURANCE',SYSDATE,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_MASTER (PROD_ID,PROD_CODE,PROD_DESCRIPTION ,PROD_START_DATE,PROD_END_DATE,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_prod_id_seq.NEXTVAL,'MARINE','Marine Cargo insurance',SYSDATE,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_MASTER (PROD_ID,PROD_CODE,PROD_DESCRIPTION ,PROD_START_DATE,PROD_END_DATE,created_by ,created_date,last_updated_by ,last_update_date )
VALUES(xxgen_prod_id_seq.NEXTVAL,'TRAVEL','Marine Cargo insurance',SYSDATE,NULL,1,sysdate,1,sysdate)
/
DROP TABLE XXGEN_PRODUCT_RISK_MASTER
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'THEFT','MOTOR2','Vehicle Theft',1.25,sysdate,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'OWNER-DEATH','MOTOR2','Vehicle Owner Accedental Death Coverage',0,sysdate,null,1,sysdate,1,sysdate)
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'VEHICLE-DAMAGE','MOTOR2','ADDITIONA DRIVER COVERAGE',0,sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'DRIVER-COVER','MOTOR2','ADDITIONA DRIVER COVERAGE',0.65,sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'THIRDPARTYACC','MOTOR2','ADDITIONA DRIVER COVERAGE',1.15,sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'BUILDING','HOME','Building Fire Coverage',1.15,sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'CONTENT','HOME','Inside Building Things coverate',2.15,sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'EARTHQUAKE','HOME','Building Coverage when EARTHQUAKE',1.25,sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_PRODUCT_RISK_MASTER
(RISK_ID,RISK_CODE   ,PROD_ID , Risk_description ,Risk_premium_percent,Risk_start_date,Risk_end_date,created_by ,created_date,last_updated_by ,last_update_date )
values(xxgen_risk_id_seq.nextval,'TERROR','HOME','Terrorist Attack coverage',1.25,sysdate,null,1,sysdate,1,sysdate)
/
INSERT INTO XXGEN_PROD_DEFAULT_RISK
(RISK_CODE ,PROD_ID , Risk_start_date ,Risk_end_date  ,created_by ,created_date,last_updated_by ,last_update_date )
VALUES('OWNER-DEATH','MOTOR2',SYSDATE,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_VEHICLE_MASTER
(MFG_COMPANY_NAME ,MODEL_ID   ,model_name ,engine_cubic_capacity ,insured_declared_value,created_by ,created_date,last_updated_by ,last_update_date)
values('HONDA','ACTIVA3G','ACTIVA 3G',120,75000,1,sysdate,1,sysdate)
/
insert into  XXGEN_VEHICLE_MASTER
(MFG_COMPANY_NAME ,MODEL_ID   ,model_name ,engine_cubic_capacity ,insured_declared_value,created_by ,created_date,last_updated_by ,last_update_date)
values('HONDA','ACTIVA4G','ACTIVA 4G',120,79000,1,sysdate,1,sysdate)
/
insert into  XXGEN_VEHICLE_MASTER
(MFG_COMPANY_NAME ,MODEL_ID   ,model_name ,engine_cubic_capacity ,insured_declared_value,created_by ,created_date,last_updated_by ,last_update_date)
values('HERO','SPLENDE','Splender 100CC',120,55000,1,sysdate,1,sysdate)
/
insert into  XXGEN_VEHICLE_MASTER
(MFG_COMPANY_NAME ,MODEL_ID   ,model_name ,engine_cubic_capacity ,insured_declared_value,created_by ,created_date,last_updated_by ,last_update_date)
values('HERO','SPLENDE+','Splender+ 110CC',100,68000,1,sysdate,1,sysdate)
/
insert into  XXGEN_VEHICLE_MASTER
(MFG_COMPANY_NAME ,MODEL_ID   ,model_name ,engine_cubic_capacity ,insured_declared_value,created_by ,created_date,last_updated_by ,last_update_date)
values('BAJAN','PULSAR120','PULSAR 120 CC BIKE',120,89000,1,sysdate,1,sysdate)
/
insert into  XXGEN_VEHICLE_MASTER
(MFG_COMPANY_NAME ,MODEL_ID   ,model_name ,engine_cubic_capacity ,insured_declared_value,created_by ,created_date,last_updated_by ,last_update_date)
values('BAJAN','PULSAR180','PULSAR 180 CC BIKE',180,97,1,sysdate,1,sysdate)
/
insert into  XXGEN_VEHICLE_MASTER
(MFG_COMPANY_NAME ,MODEL_ID   ,model_name ,engine_cubic_capacity ,insured_declared_value,created_by ,created_date,last_updated_by ,last_update_date)
values('BAJAN','PULSAR220','PULSAR 220 CC BIKE',220,97,1,sysdate,1,sysdate)
--================================================Agency =====================================================
/
insert into  XXGEN_AGEN_MASTER
(AGEN_ID,AGENT_NAME ,AGENT_DOB ,AGENT_AGE ,AGENT_QUALIFICATION ,AGENT_JOIN_DATE ,AGENT_START_DATE ,AGENT_END_DATE ,AGENT_STATUS ,created_by ,created_date,last_updated_by ,last_update_date)
VALUES(xxgen_agent_id_seq.NEXTVAL,'VENU','14/05/1983',33,'M.Sc',SYSDATE,SYSDATE+10,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_AGEN_MASTER
(AGEN_ID,AGENT_NAME ,AGENT_DOB ,AGENT_AGE ,AGENT_QUALIFICATION ,AGENT_JOIN_DATE ,AGENT_START_DATE ,AGENT_END_DATE ,AGENT_STATUS ,created_by ,created_date,last_updated_by ,last_update_date)
VALUES(xxgen_agent_id_seq.NEXTVAL,'RAVI','14/05/1985',30,'M.Sc',SYSDATE,SYSDATE+10,NULL,1,sysdate,1,sysdate)
/
insert into  XXGEN_AGEN_COMMISOIN_MASTER
(AGEN_ID,AGENT_PROD_ID,COMMISION_PERSENT,created_by,created_date,last_updated_by ,last_update_date)
VALUES (1,'MOTOR2',17.5,1,sysdate,1,sysdate)
/
insert into  XXGEN_AGEN_COMMISOIN_MASTER
(AGEN_ID,AGENT_PROD_ID,COMMISION_PERSENT,created_by,created_date,last_updated_by ,last_update_date)
VALUES (1,'HOME',20,1,sysdate,1,sysdate)
/
insert into  XXGEN_AGEN_COMMISOIN_MASTER
(AGEN_ID,AGENT_PROD_ID,COMMISION_PERSENT,created_by,created_date,last_updated_by ,last_update_date)
VALUES (2,'MOTOR2',17.5,1,sysdate,1,sysdate)
/
insert into  XXGEN_AGEN_COMMISOIN_MASTER
(AGEN_ID,AGENT_PROD_ID,COMMISION_PERSENT,created_by,created_date,last_updated_by ,last_update_date)
VALUES (2,'HOME',20,1,sysdate,1,sysdate)
/
--=====================================================ENDORSEMENT ===================================================

insert into  XXGEN_ENDORSE_MASTER
(ENDORSEMENT_CODE   ,ENDORSE_DESC ,FINANCE_IMPACT ,START_DATE,END_DATE ,created_by ,created_date,last_updated_by ,last_update_date)
values('ADD_RISK','Add New Risk','Y',sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_ENDORSE_MASTER
(ENDORSEMENT_CODE   ,ENDORSE_DESC ,FINANCE_IMPACT ,START_DATE,END_DATE ,created_by ,created_date,last_updated_by ,last_update_date)
values('INCREASE_SI','Sum Assured Increase','Y',sysdate,null,1,sysdate,1,sysdate)
/
insert into  XXGEN_ENDORSE_MASTER
(ENDORSEMENT_CODE   ,ENDORSE_DESC ,FINANCE_IMPACT ,START_DATE,END_DATE ,created_by ,created_date,last_updated_by ,last_update_date)
values('DECREASE_SI','Sum Assured Decreasing','Y',sysdate,null,1,sysdate,1,sysdate)
--================================RE-Insurance=========================================
insert into  XXGEN_RETENSION_MASTER
(RI_PROD_CODE ,RETENSION_FLAG ,MAX_RETENSION_LIMIT ,RETENSION_PERCENT,START_DATE,END_DATE,STATUS,CREATED_BY ,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
values ('HOME','F',200000000,100,SYSDATE,NULL,1,SYSDATE,SYSDATE,1)
 /
 insert into  XXGEN_RI_PRIORITY_MASTER
(PROD_CODE ,TREATY_CODE   ,TREATY_DESCRIPTION ,priority,STATUS ,START_DATE ,END_DATE DATE,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('HOME','RETENSION','HOME Retension share',1,'A',SYSDATE,NULL,1,SYSDATE,SYSDATE,1)
 /
 insert into  XXGEN_RI_PRIORITY_MASTER
(PROD_CODE ,TREATY_CODE   ,TREATY_DESCRIPTION ,priority,STATUS ,START_DATE ,END_DATE DATE,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('HOME','HOME_SURPLUS','HOME Product Suplus share',3,'A',SYSDATE,NULL,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_PRIORITY_MASTER
(PROD_CODE ,TREATY_CODE   ,TREATY_DESCRIPTION ,priority,STATUS ,START_DATE ,END_DATE CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('HOME','HOME_QUOTA','HOME product Quota share ',2'A',SYSDATE,NULL,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_MASTER
(TREATY_CODE,TREATY_NAME ,TREATY_TYPE ,TREATY_YEAR ,COMMUNICATION_CHANNEL ,TREATY_MAX_LIMIT,CURRENCY  ,STATUS ,START_DATE,END_DATE ,CREATED_BY ,CREATED_DATE ,
LAST_UPDATE_DATE ,LAST_UPDATED_BY )
VALUES('HOME_SURPLUS','HOME Product Suplus share','PROPORTION',2017,'DIRECT',30000000,'INR','A',SYSDATE,NULL,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_MASTER
(TREATY_CODE,TREATY_NAME ,TREATY_TYPE ,TREATY_YEAR ,COMMUNICATION_CHANNEL ,CURRENCY  ,STATUS ,START_DATE,END_DATE ,CREATED_BY ,CREATED_DATE ,
LAST_UPDATE_DATE ,LAST_UPDATED_BY )
VALUES('HOME_QUOTA','HOME Product QUOTA share','PROPORTION',2017,'DIRECT',60000000,'INR','A',SYSDATE,NULL,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_PARTICIPANTS
(TREATY_CODE,INSTITUTION_CODE ,INSTITUTION_BRANCH ,INSTITUTION_NAME  ,TREATY_SHARE_TYPE,TREATY_FIX_PERCENT,CREATED_BY ,CREATED_DATE,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('HOME_SURPLUS','ICICIGEN','MUMBAI','ICICI PRODETIAL','PERCENTAGE',60,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_PARTICIPANTS
(TREATY_CODE,INSTITUTION_CODE ,INSTITUTION_BRANCH ,INSTITUTION_NAME  ,TREATY_SHARE_TYPE,TREATY_FIX_PERCENT,CREATED_BY ,CREATED_DATE,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('HOME_SURPLUS','HDFCGEN','MUMBAI','HDFC ERGO GENERAL INSURANCE','PERCENTAGE',40,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_PARTICIPANTS
(TREATY_CODE,INSTITUTION_CODE ,INSTITUTION_BRANCH ,INSTITUTION_NAME  ,TREATY_SHARE_TYPE,TREATY_FIX_PERCENT,CREATED_BY ,CREATED_DATE,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('HOME_QUOTA','GENINS','MUMBAI','GEN INSURE ','PERCENTAGE',55,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_PARTICIPANTS
(TREATY_CODE,INSTITUTION_CODE ,INSTITUTION_BRANCH ,INSTITUTION_NAME  ,TREATY_SHARE_TYPE,TREATY_FIX_PERCENT,CREATED_BY ,CREATED_DATE,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('HOME_QUOTA','ORIENTAL','MUMBAI','ORIENTAL GENERAL INSURANCE','PERCENTAGE',45,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_PROPORTION
(TREATY_CODE ,ACCOUNT_PERIOD  ,PML_AMOUNT,MAXIMUM_CEDING_LIMIT ,BASE ,T_value,lines ,CREATED_BY ,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
values('HOME_QUOTA','QUARTERLY',NULL,200000000,'QUOTA' 100,NULL,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_RI_TREATY_PROPORTION
(TREATY_CODE ,ACCOUNT_PERIOD  ,PML_AMOUNT,MAXIMUM_CEDING_LIMIT ,BASE ,T_value,lines ,CREATED_BY ,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
values('HOME_SURPLUS','QUARTERLY',NULL,300000000,'QUOTA' 100,NULL,1,SYSDATE,SYSDATE,1)
/
--=====================================cLAIMS================================================================
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('SUBMIT','CLAIM SUBMITTED',1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('SURVEY','PENDING SURVEY',1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('SURVEYCOMP','SURVEY COMPLETED',1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('DOCREQ','PENIDNG REQUIRED DOCUMENTS',1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('DOCSUB','DOCUMENT SUBMITTED',1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('DOCVERIFY','DOCUMENT VERIFIED',1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('SETTELED','CLAIM SETTELED',1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIM_STATUS_MASTER(CLM_STATUS_CODE   ,CLM_STATUS_DESC ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
values('DISPUTE','CLAIM DISPUTED',1,SYSDATE,SYSDATE,1)
/
/
insert into  XXGEN_CLAIMS_SURVEYOR_MASTER
(SURVEYOR_ID  ,SURVEYOR_NAME ,SURVEYOR_QUALIFICAITION ,SURVEYOR_BRACH_CODE,SURVEYOR_CITY ,PHONE ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
VALUES(1,'Ravi kumar','B.Tech','NEWINDHYD','Hyderabad',9999999,1,SYSDATE,SYSDATE,1)
/
insert into  XXGEN_CLAIMS_SURVEYOR_MASTER
(SURVEYOR_ID  ,SURVEYOR_NAME ,SURVEYOR_QUALIFICAITION ,SURVEYOR_BRACH_CODE,SURVEYOR_CITY ,PHONE ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY )
VALUES(2,'Vinay','B.Sc','NEWINDHYD','Hyderabad',9999999,1,SYSDATE,SYSDATE,1)
--==============
INSERT INTO xxgen_NCB_MASTER
(PROD_CODE ,NO_YEARS_FROM,NO_YEARS_TO,DISCOUNT_ON_PREMIUM,DISCOUNT_DESC,
CREATED_BY,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
VALUES ('MOTOR2',0,1,20,'No claim made or pending during the preceding full year of insurance'
,1,sysdate,sysdate,1)
/
INSERT INTO xxgen_NCB_MASTER
(PROD_CODE ,NO_YEARS_FROM,NO_YEARS_TO,DISCOUNT_ON_PREMIUM,DISCOUNT_DESC,
CREATED_BY,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
VALUES ('MOTOR2',1,2,25,'No claim made or pending during the preceding 2 consecutive years of insurance 25%'
,1,sysdate,sysdate,1)
/
INSERT INTO xxgen_NCB_MASTER
(PROD_CODE ,NO_YEARS_FROM,NO_YEARS_TO,DISCOUNT_ON_PREMIUM,DISCOUNT_DESC,
CREATED_BY,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
VALUES ('MOTOR2',2,3,35,'No claim made or pending during the preceding 3 consecutive years of insurance 25%'
,1,sysdate,sysdate,1)
/
INSERT INTO xxgen_NCB_MASTER
(PROD_CODE ,NO_YEARS_FROM,NO_YEARS_TO,DISCOUNT_ON_PREMIUM,DISCOUNT_DESC,
CREATED_BY,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
VALUES ('MOTOR2',3,4,45,'No claim made or pending during the preceding 4 consecutive years of insurance 25%'
,1,sysdate,sysdate,1)
/
INSERT INTO xxgen_NCB_MASTER
(PROD_CODE ,NO_YEARS_FROM,NO_YEARS_TO,DISCOUNT_ON_PREMIUM,DISCOUNT_DESC,
CREATED_BY,CREATED_DATE,LAST_UPDATE_DATE,LAST_UPDATED_BY)
VALUES ('MOTOR2',4,5,50,'No claim made or pending during the preceding 5 consecutive years of insurance 25%'
,1,sysdate,sysdate,1)
/
--No claim made or pending during the preceding full year of insurance   20%
--No claim made or pending during the preceding 2 consecutive years of insurance 25%
--No claim made or pending during the preceding 3 consecutive years of insurance 35%
--No claim made or pending during the preceding 4 consecutive years of insurance 45%
--No claim made or pending during the preceding 5 consecutive years of insurance 50%
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE1','CHENNAI',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE1','HYDERABAD',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE1','KOLKATHA',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE1','BANGLORE',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE1','DELHI',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE1','MUMBAI',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE1','PUNE',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_GEOGRAPHICAL_ZONES
(ZONE_CODE ,ZONE_LOC   ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE,LAST_UPDATED_BY) 
VALUES ('ZONE2','REST-OF-INDIA',1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',0,5,0,999,3.127,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',0,5,1000,1499,3.283,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',0,5,1500,99999,3.440,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',0,5,0,999,3.039,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',0,5,1000,1499,3.191,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',0,5,1500,99999,3.343,1,sysdate,sysdate,1)
--====
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',5,10,0,999,3.039,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',5,10,1000,1499,3.351,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',5,10,1500,99999,3.510,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',5,10,0,999,3.283,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',5,10,1000,1499,3.447,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',5,10,1500,99999,3.612,1,sysdate,sysdate,1)
/
--=========
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',11,99,0,999,3.267,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',11,99,1000,1499,3.430,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE2',11,99,1500,99999,3.594,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',11,99,0,999,3.362,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',11,99,1000,1499,3.529,1,sysdate,sysdate,1)
/
INSERT INTO XXGEN_OWN_DAMAGE_COVER_PREM
(PROD_CODE ,ZONE_CODE,VEHICLE_age_from ,VEHICLE_age_to ,vehicle_CC_from ,VEHICLE_CC_TO,
prem_percent_on_idv ,CREATED_BY ,CREATED_DATE ,LAST_UPDATE_DATE ,LAST_UPDATED_BY)
VALUES('MOTOR2','ZONE1',11,99,1500,99999,3.698,1,sysdate,sysdate,1)
/
--======================================================Transaction Tables ======================================================
/
DROP TABLE XXGEN_INSURED_DTLS
/
insert into  XXGEN_INSURED_DTLS
(INSURED_ID  ,
INSURED_NAME ,
INSURED_DOB DATE,
INSURED_PHONE ,
INSURED_QUALIFICATION ,
INSURED_PROFISSION ,
INSURED_ADDR_CODE ,--FK 
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY 
)
/
DROP TABLE XXGEN_INSURED_ADDRESS
/
insert into  XXGEN_INSURED_ADDRESS
(INSURED_ADDR_ID NUMBER ,
INSURED_ID ,
ADDRESS_TYPE ,--TEMPORARY OR PERMANENT
ADDRESS_STATUS ,
INSURED_ADDR1    ,
INSURED_ADDR2    ,
INSURED_CITY    ,
INSURED_SATE    ,
INSURED_COUNTRY    ,
INSURED_PINCODE    ,
Phone        number(15),
email        ,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (INSURED_ID) REFERENCES XXGEN_INSURED_DTLS(INSURED_ID)
)
/
DROP TABLE XXGEN_POLICY_DTLS
/
insert into  XXGEN_POLICY_DTLS
(POLICY_NO  ,
INSURED_ID , --FK of XXGEN_INSURED_DTLS
PROD_CODE ,
POLICY_ISSUED_DATE DATE,
START_DATE DATE,
END_DATE DATE,
POLICY_STATUS ,--QUOTATION,PENDINGPREMIUM,ISSUED,INFORCE,LAPSE
RENEWAL_NO ,
PAYMENT_OPTION ,
TOTAL_PREMIUM NUMBER(20,1),  --SUM OF RISK PREMIUM
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (INSURED_ID) REFERENCES XXGEN_INSURED_DTLS(INSURED_ID),
FOREIGN KEY (PROD_CODE) REFERENCES XXGEN_PRODUCT_MASTER(PROD_CODE)
)
/
DROP TABLE XXGEN_POLICY_RISk_DTLS
/
insert into  XXGEN_POLICY_RISk_DTLS
(POLICY_RISK_ID  , 
POLICY_NO , --FK of XXGEN_POLICY_DTLS
RISK_CODE , 
Risk_description ,
Risk_premium DATE,
START_DATE DATE,
END_DATE DATE,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (POLICY_NO) REFERENCES XXGEN_POLICY_DTLS(POLICY_NO),
FOREIGN KEY (RISK_CODE) REFERENCES XXGEN_PRODUCT_RISK_MASTER(RISK_CODE)
)
/
DROP TABLE XXGEN_POLICY_ENDORSE_DTLS
/
insert into  XXGEN_POLICY_ENDORSE_DTLS
(ENDORSE_ID , --pK 
POLICY_NO ,--FK
ENDORSE_CODE , 
Endorse_desc ,
ENDORSE_DATE DATE,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (POLICY_NO) REFERENCES XXGEN_POLICY_DTLS(POLICY_NO)
)
/
DROP TABLE XXGEN_POLICY_VEHICLE_DTLS
/
insert into  XXGEN_POLICY_VEHICLE_DTLS
(VEHICLE_ID  , 
POLICY_NO ,
VEHICLE_YEAR ,
VEHICLE_MAKE ,
VEHICLE_MODEL ,  
COLOR ,
MILAGE NUMBER(10,2),
CHASIS_NUMBER ,
ENGINE_NUMBER NUMBER(15),
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (POLICY_NO) REFERENCES XXGEN_POLICY_DTLS(POLICY_NO)
)
/
DROP TABLE XXGEN_POLICY_DRIVER_DTLS
/
insert into  XXGEN_POLICY_DRIVER_DTLS
(DRIVER_ID ,
POLICY_NO , --fK
FIRST_NAME ,
LAST_NAME  ,
DRIVER_DOB  DATE,
PHONE_NO NUMBER(15),
LICENSE_NO ,
LICENSE_ISSUE_DATE DATE,
LICENSE_ISSUE_STATE ,
IS_PRIMARY_POLICY_HOLDER ,
REL_WITH_POLICY_HOLDER ,
GENDER ,
MARITAL_STATUS ,
STATUS ,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (POLICY_NO) REFERENCES XXGEN_POLICY_DTLS(POLICY_NO)
)
/
DROP TABLE XXGEN_VEHICLE_DRIVER
/
insert into  XXGEN_VEHICLE_DRIVER
(VDID  , --PK
VEHICLE_ID , --FK  OF XXGEN_POLICY_VEHICLE_DTLS
DRIVER_ID ,--FK OF XXGEN_POLICY_DRIVERS_TLS
DRIVER_FOR_BUSINESS , 
IS_PRIMARY_DRIVER ,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (VEHICLE_ID) REFERENCES XXGEN_POLICY_VEHICLE_DTLS(VEHICLE_ID),
FOREIGN KEY (DRIVER_ID) REFERENCES XXGEN_POLICY_DRIVER_DTLS(DRIVER_ID)
)
/
DROP TABLE XXGEN_DRIVER_TRAFIC_VILATIONS
/
insert into  XXGEN_DRIVER_TRAFIC_VILATIONS
(VILATION_ID  , --PK
DRIVER_ID , --FK  OF XXGEN_POLICY_VEHICLE_DTLS
VILATION_DATE DATE,--FK OF XXGEN_POLICY_DRIVERS_TLS
VILATION_PLACE , 
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (DRIVER_ID) REFERENCES XXGEN_POLICY_DRIVER_DTLS(DRIVER_ID)
)
/
DROP TABLE XXGEN_POLICY_BILLS
/
insert into  XXGEN_POLICY_BILLS
(BILL_ID  , --PK
POLICY_NO ,
PREMIUM_AMOUNT NUMBER(20,2), 
DUE_DATE DATE,
BALANCE_AMOUNT NUMBER(20,2), 
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (POLICY_NO) REFERENCES XXGEN_POLICY_DTLS(POLICY_NO)
)
/
DROP TABLE XXGEN_POLICY_PAYMENT_DTLS
/
insert into  XXGEN_POLICY_PAYMENT_DTLS
(PAYMENT_ID , --PK
BILL_ID ,
PAID_AMOUNT NUMBER(20,2),  
PAID_DATE DATE, 
DUE_DATE DATE,
PAY_METHID ,
FIRST_NAME ,
LAST_NAME ,
CARD_NUMBER NUMBER(16),
ZIP ,
CARD_EXP_DATE DATE,
CARD_TYPE ,
DEBIT_OR_CREDIT ,
BANK_NAME ,
ACCOUNT_NO ,
CHECK_NUMBER ,
CHECK_IMAGE CLOB,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (BILL_ID) REFERENCES XXGEN_POLICY_BILLS(BILL_ID)
)
/
DROP TABLE XXGEN_CLAIMS
/
insert into  XXGEN_CLAIMS
(CLAIM_ID  , --PK
POLICY_NO , --FK
CLAIM_DATE DATE,
AMOUNT_CLAIMED NUMBER(20,2),
AMOUNT_SETTELED NUMBER(20,2),
DATE_OF_SETTELE DATE,
TOTAL_POLICY_AMOUNT NUMBER(20,2),
TOTAL_CLAIM_AMOUNT NUMBER(20,2),
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (POLICY_NO) REFERENCES XXGEN_POLICY_DTLS(POLICY_NO)
)
/
DROP TABLE XXGEN_CLAIMS_PROCESS_DTLS
/
insert into  XXGEN_CLAIMS_PROCESS_DTLS
(CLM_PROCESS_ID ,--PK
CLAIM_ID , --PK
POLICY_NO , --FK
CLAIM_DATE DATE,
AMOUNT_CLAIMED NUMBER(20,2),
AMOUNT_SETTELED NUMBER(20,2),
DATE_OF_SETTELE DATE,
TOTAL_POLICY_AMOUNT NUMBER(20,2),
TOTAL_CLAIM_AMOUNT NUMBER(20,2),
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (POLICY_NO) REFERENCES XXGEN_POLICY_DTLS(POLICY_NO),
FOREIGN KEY (CLAIM_ID) REFERENCES XXGEN_CLAIMS(CLAIM_ID)
)
/
DROP TABLE XXGEN_CLAIMS_SURVEYOR_DTLS
/

insert into  XXGEN_CLAIMS_SURVEYOR_DTLS
(SURVEYOR_ID , --FK
surveyor_name ,
CLAIM_ID , --PK
Surveyor_claim_amount number(20,2),
documents_description ,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (CLAIM_ID) REFERENCES XXGEN_CLAIMS(CLAIM_ID),
FOREIGN KEY (SURVEYOR_ID) REFERENCES XXGEN_CLAIMS_SURVEYOR_MASTER(SURVEYOR_ID)
)
/
DROP TABLE XXGEN_CLAIMS_DOCS
/
insert into  XXGEN_CLAIMS_DOCS
(CLAIM_DOC_ID  , --PK
CLAIM_ID ,
doc_type_code ,
doc_description ,
CREATED_BY ,
CREATED_DATE date,
LAST_UPDATE_DATE DATE,
LAST_UPDATED_BY ,
FOREIGN KEY (CLAIM_ID) REFERENCES XXGEN_CLAIMS(CLAIM_ID)
)
